### ISSUE TITLE
Check version of Ontology referenced in spek

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/bit-stomach#1]
* Track the version of FIDO was that was last baked into the internal configuration of bitstomach.
* Warn if the version of FIDO referenced in the spek is different.

This issue depends on FIDO being versioned and published.

**Comment by CooperStansbury** [comment]
@grosscol let's find a time to chat about FIO versioning this week.

**Comment by grosscol** [comment]
See https://github.com/Display-Lab/fio/issues/143

**Comment by grosscol** [comment]
If the input spek references an ontology with a version, make sure that version is maintained in the output spek.

**Comment by grosscol** [comment]
This will be made irrelevant by encapsulating all of the URI constants in spekex.
